### ISSUE TITLE
Running and converting .pkl

### ISSUE THREAD

**Issue by saadqu** [bjekic/WallSegmentation#10]
Hi,
I am new to this area can anyone point me in the direction of how can I run this model? I have tried Jupyter but somehow only a single file is runable on Jupyter and gives dependencies error.
Also, I would like this model to be converted into an onx file, is it possible or do I have to train again with some other config please do let me know.
Thanks

**Comment by bjekic** [comment]
Hi saadqu,

Can you provide a traceback of the error you are encountering when running any script/notebook and specify what did you exactly run.

Regarding the conversion to onnx, there is no support for model conversion and deployment of this model inside this repository.

**Comment by bjekic** [comment]
Hi @saadqu,

You can take a look at the official pytorch docs for model conversion, for example this [link](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html#optional-exporting-a-model-from-pytorch-to-onnx-and-running-it-using-onnx-runtime).

Since there are no other issues with the repository itself, I will we closing this issue.
